runtime: nodejs22

instance_class: F2

automatic_scaling:
  max_instances: 20
  min_instances: 1

service: portfolioapp

handlers:
  # Sert les fichiers statiques correctement (js, css, fonts, images, etc.)
  - url: /(.*\.(js|css|png|jpg|jpeg|gif|ico|svg|webp|woff2?|ttf|eot|otf|json|html|glb))
    static_files: \1
    upload: (.*)

  # Redirige toutes les autres requêtes vers index.html (pour le routing Angular)
  - url: /.*
    static_files: index.html
    upload: index.html
